DEBUG = False
START_EPOCH = 2000

EXPLORE_PROB = .2
POOL_SIZE = 256
VIEW_RATIO = .05
ATTITUDE_TOWARDS_NOVEL_TAGS = 1

JOB_POOL_SIZE = 8
JOB_POOL_THROTTLE = 3
JSON_MAX = 256
PORT = 2348

FILTER = ''

# Below are default values. 
# DEBUG = False
# START_EPOCH = 2000

# EXPLORE_PROB = .2
# POOL_SIZE = 256
# VIEW_RATIO = .05
# ATTITUDE_TOWARDS_NOVEL_TAGS = 1

# JOB_POOL_SIZE = 8
# JOB_POOL_THROTTLE = 3
# JSON_MAX = 256
# PORT = 2348

# FILTER = ''
